[phases.setup]
nixPkgs = ["python39", "python39Packages.pip", "python39Packages.setuptools", "python39Packages.wheel", "gcc"]

[phases.install]
cmds = ["python -m pip install -r requirements.txt", "python -m spacy download en_core_web_sm"]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
